name: fileUpdate

on:
    push:
        
jobs:

    fileUpdate:
        runs-on: ubuntu-latest
        steps:
        
        - name: Clonar repositorio
          uses: actions/checkout@v2
          
        - name: Comprobar OPENSSL
          run:  cat ./etc/ssl/openssl.cnf
          
        - name: Ejecutar el script de shell para la descarga de ficheros
          run: ./data.sh
          
        - name: Push a Github
          run: |
            git config --global user.name "${{ secrets.GIT_USERNAME }}"
            git config --global user.email "${{ secrets.GIT_MAIL }}"
            git add .
            git commit -m "${{ secrets.GIT_MESSAGE }}"
            git push
